### ISSUE TITLE
Fork and patch libp11 to prevent listing all keys?

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nethsm-pkcs11#106]

**Comment by nponsard** [comment]
Create an issue on upstream to see what they think of the issue

**Comment by jans23** [comment]
To ask upstream and relevant user.

**Comment by nponsard** [comment]
https://github.com/OpenSC/libp11/issues/512

**Comment by nponsard** [comment]
Spend a day trying to apply the fix mentioned in the answer

**Comment by nponsard** [comment]
was fixed here : https://github.com/OpenSC/libp11/commit/21209b117bd0c0e96d27f2ea16a6b0940d4af7c0
