### ISSUE TITLE
Build for Fedora release 39 (x86_64)

### ISSUE THREAD

**Issue by aio-witc** [Nitrokey/nethsm-pkcs11#152]
Fedora 39 has been released in November 2023:
    https://docs.fedoraproject.org/en-US/releases/f39/

https://github.com/Nitrokey/nethsm-pkcs11/releases has only a build for Fedora 38.

We'd love to see an official Fedora 39 [x86_64] build.

Best regards
wiwi

**Comment by daringer** [comment]
Quick fix would be adding `fedora:39` here: https://github.com/Nitrokey/nethsm-pkcs11/blob/ed449b6e6b348198e8b2cf36758e215545432833/.github/workflows/release.yml#L80C43-L80C55
