### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nethsm-pkcs11#154]
In particular ~golang.org/x/crypto and~ unsafe-libyaml should be updated.

**Comment by ansiwen** [comment]
@jans23 what do you mean? We are not using Go anymore.

**Comment by jans23** [comment]
Right. Actually the issue is that Dependabot complains about these. Is there a way to exclude Dependabot from the Go branch?

**Comment by robin-nitrokey** [comment]
I don’t know why the Go code is checked at all.  According to the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#about-updates-for-vulnerable-dependencies-in-your-repository), only the default branch should be checked:

> GitHub generates Dependabot alerts when we detect that the default branch of your codebase is using dependencies with known security risks.
