### ISSUE TITLE
better CK_INFO values

### ISSUE THREAD

**Issue by aio-witc** [Nitrokey/nethsm-pkcs11#158]
- libraryVersion should be 1.0 _(is currently 0.1)_
- libraryDescription should mention "NetHSM", maybe: "Nitrokey NetHSM PKCS#11 library" - 31 chars, would fit ;-) or: "NetHSM PKCS#11 library", "Nitrokey" is manufacturerID _- is currently "Nitrokey PKCS#11 library" - which could cause misunderstandings, as Nitrokey has much more devices, that could use PKCS11 - e.g. NitroKeys, NitroHSM, ...)_
- (not important:) manufacturerID - "nitrokey.com" or "Nitrokey GmbH"? _(is currently "Nitrokey")_ 

Possible location: https://github.com/Nitrokey/nethsm-pkcs11/blob/ed449b6e6b348198e8b2cf36758e215545432833/pkcs11/src/defs.rs#L9-L11

**Comment by robin-nitrokey** [comment]
I suggest these changes:
- `LIB_VERSION` should just be derived from the crate version.
- `LIB_DESCRIPTION` should include `NetHSM`.
- `LIB_MANUFACTURER` should be `Nitrokey GmbH`.
