### ISSUE TITLE
Make it possible to implement integration tests

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nethsm-pkcs11#166]
Since the module is a `cdylib` it is not possible to have integration tests on the main crate.

I suggest splitting the crate into a normal rust crate and a `cdylib` that just reexports it that way integration testing is possible.

**Comment by robin-nitrokey** [comment]
What kind of integration tests would you like to add?

Generally, I think it would make sense to split the code into the unsafe C API that just does the data mapping, and a safe Rust API that returns `Result<_, CK_RV>`.  That would also make the code much more ergonomic.  Potentially, macros could be used to reduce the amount of boilerplate code.  (See also: https://github.com/Nitrokey/nethsm-pkcs11/issues/138)

**Comment by sosthene-nitrokey** [comment]
I wanted to add  tests that used different config files to test #165 on bad files, fingerprints etc... I can't do that in the normal tests because the `env::set_var` is global and the device is only initialized once, so I need a specific test executable for each test.

**Comment by robin-nitrokey** [comment]
Maybe the change to `C_Initialize`/`C_Finalize` I suggested in that PR would already be enough for testing that?  I’m not opposed to splitting the crate, but as it adds additional release and maintenance effort, I would first try out simpler solutions.

**Comment by sosthene-nitrokey** [comment]
That would require serializing all the tests.

**Comment by robin-nitrokey** [comment]
Would that be an issue?  I think if we really want integration tests for a library with a global state, we need sequential tests.  If you only want to test the init implementation without the PKCS11 wrapper, you could also test `read_configuration` directly (and move the env access out of that function).

**Comment by robin-nitrokey** [comment]
You will probably run into issues with repeated calls to `log::set_logger` if you also test applying the configuration.

**Comment by sosthene-nitrokey** [comment]
I was able to implement this in 4157673d9c3078cab319298384d79fb9e8e6e6f9

**Comment by sosthene-nitrokey** [comment]
Some form of integration tests have been implemented as part of https://github.com/Nitrokey/nethsm-pkcs11/pull/214
