### ISSUE TITLE
Complete documentation for p11nethsm.conf

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/nethsm-pkcs11#168]
Hi! :wave: 

I have just packaged this project for Arch Linux and while doing so I noticed, that there is no extensive documentation of the configuration file.
It would be *very good* to provide one example configuration file, which outlines and documents *all possible features*. Additionally, it would also be good to version this configuration file format, so that people are able to understand which features they may use.

Currently users can only deduce a somewhat more full picture of available options from looking at https://docs.nitrokey.com/nethsm/pkcs11-setup.html#configuration-file-format, https://github.com/Nitrokey/nethsm-pkcs11/blob/58d8b5f90a4299eecf51f789c87a063dbd8c8198/container/nginx/p11nethsm.conf, https://github.com/Nitrokey/nethsm-pkcs11/blob/58d8b5f90a4299eecf51f789c87a063dbd8c8198/container/apache/p11nethsm.conf and https://github.com/Nitrokey/nethsm-pkcs11/blob/58d8b5f90a4299eecf51f789c87a063dbd8c8198/p11nethsm.conf.

From a usability perspective, this is not great and a central example file with documentation would be much appreciated (also for packaging purposes!).

**Comment by sosthene-nitrokey** [comment]
#172 Adds a config file with all options, and documents them. It contains some not yet released optons, and will be synchronised with https://docs.nitrokey.com/nethsm/pkcs11-setup.html#configuration-file-format

**Comment by jans23** [comment]
@sosthene-nitrokey can this be closed?

**Comment by sosthene-nitrokey** [comment]
FIxed by https://github.com/Nitrokey/nitrokey-documentation/pull/215 and https://github.com/Nitrokey/nethsm-pkcs11/pull/172
