### ISSUE TITLE
Retries: clarify interaction between retries and instances

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nethsm-pkcs11#209]
Currently, retries happen only in a single instance. #202 will make the retries change instance, but this will still make it that if `retries < num_instances`, some instances could never be tried.

**Comment by jans23** [comment]
Is this solved by https://github.com/Nitrokey/nitrokey-documentation/pull/282 ?

**Comment by sosthene-nitrokey** [comment]
No, it's another documentation change, that's slightly pendingo on https://github.com/Nitrokey/nethsm-pkcs11/pull/223

**Comment by sosthene-nitrokey** [comment]
Will be documented in https://github.com/Nitrokey/nitrokey-documentation/pull/284
