### ISSUE TITLE
A potential version fits for no_std environment

### ISSUE THREAD

**Issue by RuixiangJiang** [Nitrokey/nethsm-pkcs11#226]
Greetings! I'm quite interested in this repo, and I'm a developer dealing with a very simple OS without `std` environment. I wonder will your team develop a new version that supports `#![no_std]`? Thanks in advance.

**Comment by jans23** [comment]
Hello! Interesting question. No, we don't plan a no-std version anytime soon.

**Comment by sosthene-nitrokey** [comment]
If you want to make use of the nethsm in a no-std context, it is possible to use the [NetHSM API](https://nethsmdemo.nitrokey.com/api_docs/index.html#/) directly, using an embedded HTTP client such as [edge-net](https://crates.io/crates/edge-net) or [reqwless](https://crates.io/crates/reqwless).

**Comment by RuixiangJiang** [comment]
Thank you very much for being so responsive and helpful! The OS that I'm working in is too simple to use the Internet... And I can't execute something like `cargo` or `docker` in the command line...

**Comment by sosthene-nitrokey** [comment]
I think you are mistaken in what NetHSM provides. The NetHSM device sits in its own enclosure and only exposes its API through the network. If your device does not have a network interface, you will not be able to make use of the NetHSM.

**Comment by RuixiangJiang** [comment]
Got it. Thanks very much for your explanation!
