### ISSUE TITLE
Incompatible with OpenDNSSEC 2.1.13 : key handles are not shared between sessions

### ISSUE THREAD

**Issue by nponsard** [Nitrokey/nethsm-pkcs11#57]
If we don't have any answer from the OpenDNSSEC team we would have to change the implementation to have one unique object Db per Token/Slot.

OpenDNSSEC issue : https://issues.opendnssec.org/browse/SUPPORT-286

**Comment by jans23** [comment]
Can we add an option to support this (which would be disabled by default)?

**Comment by nponsard** [comment]
Adding an option like that would add more complexity in the code.
The mitigation for this problem is to have one single cache per NetHSM/Slot instead of a cache per session. We could just change the cache to be per slot and that would work for every application. The only drawback being that the cache may stay invalid for longer and that could be fixed by a better handling of errors.

**Comment by jans23** [comment]
Sounds fine for me.
