### ISSUE TITLE
Future plans 

### ISSUE THREAD

**Issue by nponsard** [Nitrokey/nethsm-pkcs11#59]
This issue is here to discuss the next features and functionalities to be implemented.

1. ~~OpenDNSSEC compatibility : #57 It seems unlikely that the OpenDNSSEC implementation will change in the next month, so if we want to support it this year, we will need to adapt to it.~~
2. WIP : Openapi generation : Currently I applied a bunch of patches on top of the generated crate, I would need to either create a repeatable patch or customise the openapi code generator.
3. ~~Concurrency : currently everything is blocking, but there's a concurrency option in the PKCS11 specification and not supporting it may cause problems ?~~ 
4. ~~Key listing is slow : currently we fetch one key at a time because of the blocking architecture and the NetHSM api that list keys only returns the names. One solution would be to do concurrent api calls.~~
5. ~~State management : C_GetOperationState and C_SetOperationState are functions that can be used to pause and resume cryptographic operations. This could be implemented but would require some design on how we store all this information (serialisation).~~
6. ~~Notify : the PKCS11 spec as a field where you can pass a function to be called back when certain events happen. This would require polling the NetHSM regularly to check for events.~~
7. ~~C_WaitForSlotEvent : same as 6.~~
8. ~~Certificates : Currently I'm trying for every key to get the certificate and adding it to the list of keys when it works. Should I look for certificates only when a request for certificate objects is made ? This may break some programs.~~
9. ~~Need to figure out how to do unit testing of the functions.~~
10. ~~Proper handling of the CKF_LIBRARY_CANT_CREATE_OS_THREADS, currently we can't support this flag so CKR_NEED_TO_CREATE_THREADS should be returned. We could become compatible by using ureq.~~

**Comment by jans23** [comment]
Regarding 2: Note that we use openapi generation for other implementations too (e.g. pynitrokey but also recommend it to users directly). Hence, a solution which is not limited to this pkcs11 module would be preferred,

**Comment by nponsard** [comment]
> Regarding 2: Note that we use openapi generation for other implementations too (e.g. pynitrokey but also recommend it to users directly). Hence, a solution which is not limited to this pkcs11 module would be preferred,

The problem comes from the generator that is language-specific, so it wouldn't help with the python version for example.

**Comment by ansiwen** [comment]
Ad 1) Could we use a deterministisc keyhandle generated from the key-id? If not, I think we could make the key-handle->key-id mapping global, in a structure that is initialized when the module is loaded. (So not per session but per module lifetime.)

**Comment by ansiwen** [comment]
Ad 2) the generator allows templating to customize the generated code.

**Comment by ansiwen** [comment]
Ad 3) the calls are always "blocking", they cannot yield. But PKCS11 allows to concurrently call the functions concurrently from several threads. So we would need to synchronize access to all data, that is mutable and shared between calls, like session data and so on.

**Comment by nponsard** [comment]
> Ad 3) the calls are always "blocking", they cannot yield. But PKCS11 has a feature that allows to call the functions concurrently from several threads. So, in order to support that feature, we would need to synchronize access to all data, that is mutable and shared between calls, like session data and so on. Best is of course to minimize mutable data.

I think Rust imposes a thread-safe behavior so this could already work then.

**Comment by ansiwen** [comment]
Ad 3)

> A consequence of the fact that a single session can, in general, perform only one operation at a time is that an application should never make multiple simultaneous function calls to Cryptoki which use a common session.  If multiple threads of an application attempt to use a common session concurrently in this fashion, Cryptoki does not define what happens.  This means that if multiple threads of an application all need to use Cryptoki to access a particular token, it might be appropriate for each thread to have its own session with the token, unless the application can ensure by some other means (e.g., by some locking mechanism) that no sessions are ever used by multiple threads simultaneously.  This is true regardless of whether or not the Cryptoki library was initialized in a fashion which permits safe multi-threaded access to it.  Even if it is safe to access the library from multiple threads simultaneously, it is still not necessarily safe to use a particular session from multiple threads simultaneously.

See [here](http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759996).

So session data does not have to be synchronized. Concurrent threads need to open separate sessions anyway.

**Comment by ansiwen** [comment]
> I think Rust imposes a thread-safe behavior so this could already work then.

I doubt this is true in this scenario, because the application that calls the functions is out of reach of the Rust compiler. If I call a function, that is implemented in Rust, from two concurrent threads, and that Rust implementation has mutable data, there will be a race condition. (The borrow checker can't see that race.)

**Comment by nponsard** [comment]
The tool I'm using to have data shared between function calls, `lazy_static` refuses to have shared mutable data that isn't protected by a mutex.

**Comment by ansiwen** [comment]
> The tool I'm using to have data shared between function calls, `lazy_static` refuses to have shared mutable data that isn't protected by a mutex.

And that tool supports calls from non-rust calls? So it in general does not allow shared data between functions calls? (So I guess it's a kind of reentrant safety checker?)

**Comment by ansiwen** [comment]
And anyway, as I wrote befor: if the mutable data is all within the session data, we are safe anyway, because sessions are single-thread only.
