### ISSUE TITLE
Store SDK crate in separate repository

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nethsm-pkcs11#64]

**Comment by nponsard** [comment]
Should we store a copy of the openapi specification in the repository of the crate or should we always generate the code from a remote openapi specification (e.g. https://nethsmdemo.nitrokey.com/api_docs/nethsm-api.yaml) ?

**Comment by jans23** [comment]
I prefer the usage of remote openapi specification so that always the latest version is used.
