### ISSUE TITLE
support ECDSA with internal hashing

### ISSUE THREAD

**Issue by nponsard** [Nitrokey/nethsm-pkcs11#80]
The hashing will be done on the host machine and not on the NetHSM

**Comment by jans23** [comment]
I'm wondering if users could be confused and expect the NetHSM performing the hashing. Hence, shouldn't we add a note in features.md that the hashing is done within PKCS#11 module?

**Comment by nponsard** [comment]
I'm gonna add a list of the supported mechanisms and add a note about internal hashing.
